<b> Analysis of City of Pittsburgh employee salary data from 2018 </b>

In [299]:
import pandas as pd

In [300]:
import os

↑ Loading in pandas and os

In [301]:
os.getcwd()

'/Users/Dale/Desktop/PublicSource/city_salaries_2018'

In [302]:
os.listdir(os.getcwd())

['city_salaries_2018.csv',
 'README.md',
 'analysis_city_2018.ipynb',
 '.ipynb_checkpoints',
 '.git']

↑ figuring out where my files are (lol)

↓ loading the 2018 city salary data into a DataFrame

In [303]:
pd.read_csv("city_salaries_2018.csv")

,Name,Department,Division (if applicable),Job Title,Date Started,Cur Pos Date,Date Term.,Years of Experience,Sex,Employment Status,Ethnic Code,Regular Pay,Premium Pay,Other Pay,Total Pay
0,Harry J Scherer,PS - Fire Bureau,PS-Fire-Gen Office,Deputy Chief,1/28/1980,5/17/2004,NaN,39,M,Full-time,White,"$120,645.87","$96,982.07",$0.00,"$217,627.94"
1,Jerome R Wasek,PS - Emergency Medical Services,PS-Emergency Medical Service,Crew Chief,10/31/1988,2/9/1997,NaN,30,M,Full-time,White,"$70,136.27","$145,649.73",$0.00,"$215,786.00"
2,Anthony N Desantis,PS - Emergency Medical Services,PS-Emergency Medical Service,Paramedic 5th Year,7/5/1994,1/1/2000,NaN,24,M,Full-time,White,"$64,842.21","$148,437.87",$0.00,"$213,280.08"
3,Francis M Rende,PS - Police Bureau,PS- Zone 2-Hill Dist,Master Police Officer,7/5/1993,4/29/2013,NaN,25,M,Full-time,White,"$81,883.15","$128,129.63",$0.00,"$210,012.78"
4,Robert J Cox,PS - Fire Bureau,PS-Fire-Gen Office,Deputy Chief,4/24/1995,1/21/2016,NaN,23,M,Full-time,White,"$112,194.61","$92,989.35",$0.00,"$205,183.96"
5,May G Fong,PS - Police Bureau,PS- Zone 3-Southside,Police Sergeant,9/6/1983,7/7/1995,NaN,35,F,Full-time,Asian,"$85,921.60","$113,059.78",$0.00,"$198,981.38"
6,Terry A Pryor,PS - Police Bureau,PS- Zone 2-Hill Dist,Police Officer 4th Year,2/5/2007,2/5/2010,NaN,12,M,Full-time,Black or African-American,"$70,211.96","$127,485.59",$0.00,"$197,697.55"
7,Police Officer Detective,PS - Police Bureau,PS-Police-Major Crimes,Police Officer/Detective,7/5/1993,4/6/1998,NaN,25,M,Full-time,White,"$76,043.33","$120,759.19",$480.00,"$197,282.52"
8,Igor S Boyko,PS - Police Bureau,PS- Zone 2-Hill Dist,Police Officer 4th Year,2/5/2007,2/5/2010,NaN,12,M,Full-time,White,"$69,169.19","$124,404.33",$480.00,"$194,053.52"
9,Mark B Gasiorowski,PS - Fire Bureau,PS-Fire-Gen Office,Deputy Chief-2010,8/9/1999,8/20/2018,NaN,19,M,Full-time,White,"$94,742.92","$98,779.85",$240.00,"$193,762.77"
10,Michael J Mullen,PS - Fire Bureau,PS-Fire-Gen Office,Deputy Chief,12/18/1974,5/12/2008,NaN,44,M,Full-time,White,"$120,126.39","$73,550.72",$0.00,"$193,677.11"
11,Sean E Duffy,PS - Police Bureau,PS-Special Deployment Div,Police Sergeant,4/9/1990,9/25/1998,NaN,28,M,Full-time,White,"$87,119.83","$104,837.48",$0.00,"$191,957.31"
12,Dominick C Sciulli,PS - Police Bureau,PS-Warrant Office,Police Lieutenant,1/14/2004,7/27/2015,NaN,15,M,Full-time,White,"$91,617.23","$96,509.35",$0.00,"$188,126.58"
13,Police Officer Detective,PS - Police Bureau,PS-Police-Narcotics/Vice,Police Officer/Detective,2/20/1995,4/13/2004,NaN,24,M,Full-time,White,"$74,511.38","$107,063.52",$0.00,"$181,574.90"
14,Glenn E Aldridge,PS - Police Bureau,PS-Special Deployment Div,Master Police Officer,4/17/1989,4/17/2004,NaN,29,M,Full-time,Black or African-American,"$76,511.00","$103,380.71",$0.00,"$179,891.71"
15,Gregory S Tersine,PS - Emergency Medical Services,PS-Emergency Medical Service,Crew Chief,10/17/2005,9/11/2011,NaN,13,M,Full-time,White,"$63,885.87","$115,050.66",$0.00,"$178,936.53"
16,Roy C Mcdonald,PS - Fire Bureau,PS-Fire-Gen Office,Battalion Chief,3/23/1987,1/9/2006,NaN,31,M,Full-time,White,"$111,281.70","$66,665.78",$240.00,"$178,187.48"
17,Phillip A Carey,PS - Police Bureau,PS-Chief Of Police,Police Sergeant,1/16/1995,2/22/2018,NaN,24,M,Full-time,Black or African-American,"$84,180.05","$90,894.68",$0.00,"$175,074.73"
18,Chad M O'Brien,PS - Police Bureau,PS- Zone 2-Hill Dist,Police Lieutenant,1/24/2005,8/16/2017,NaN,14,M,Full-time,White,"$92,761.81","$80,335.92",$0.00,"$173,097.73"
19,Daniel A Berg,PS - Emergency Medical Services,PS-Emergency Medical Service,Paramedic 5th Year,10/17/2005,10/17/2009,NaN,13,M,Full-time,White,"$66,616.97","$105,444.36",$0.00,"$172,061.33"
20,Antwain R Carter,PS - Emergency Medical Services,PS-EMS Admin,District Chief,1/3/1995,9/10/2018,NaN,24,M,Full-time,Black or African-American,"$74,101.11","$94,901.92",$0.00,"$169,003.03"
21,William S Hohos,PS - Police Bureau,PS- Zone 2-Hill Dist,Police Sergeant,7/5/1993,1/14/2005,NaN,25,M,Full-time,White,"$83,651.43","$85,030.95",$240.00,"$168,922.38"
22,Jeffrey C Vesci,PS - Emergency Medical Services,PS-Emergency Medical Service,Paramedic 5th Year,6/19/1989,1/1/2000,NaN,29,M,Full-time,White,"$61,941.06","$106,674.05",$0.00,"$168,615.11"
23,Joseph F Tersak,PS - Police Bureau,PS-Special Deployment Div,Police Lieutenant,4/4/1988,12/15/2003,NaN,30,M,Full-time,White,"$94,863.81","$71,259.87",$0.00,"$166,123.68"
24,James A Yauch,PS - Police Bureau,PS- Zone 6-West End,Police Sergeant,10/29/2007,11/9/2015,NaN,11,M,Full-time,White,"$80,444.96","$83,980.13",$0.00,"$164,425.09"
25,Richard E Mcclain,PS - Police Bureau,PS- Zone 2-Hill Dist,Master Police Officer,8/13/1990,3/1/2010,NaN,28,M,Full-time,Black or African-American,"$75,733.67","$88,276.25",$0.00,"$164,009.92"
26,Jeffrey W Dean,PS - Police Bureau,PS- Zone 5-East Liberty,Master Police Officer,1/4/1988,1/4/2003,NaN,31,M,Full-time,Black or African-American,"$77,665.68","$83,791.18",$0.00,"$161,456.86"
27,Patrick J Winterhalter,PS - Police Bureau,Tru (Telephone Repor,Police Officer 4th Year,3/17/2014,3/17/2017,NaN,4,M,Full-time,White,"$66,134.86","$95,046.61",$0.00,"$161,181.47"
28,Joseph S Nicholas,PS - Police Bureau,PS- Zone 2-Hill Dist,Master Police Officer,2/20/1995,3/1/2010,NaN,24,M,Full-time,White,"$79,069.37","$80,642.19",$0.00,"$159,711.56"
29,Kevin L Kenney,PS - Police Bureau,PS- Zone 6-West End,Master Police Officer,9/25/1989,9/25/2004,NaN,29,M,Full-time,Black or African-American,"$79,561.11","$79,795.90",$0.00,"$159,357.01"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4112,Joan Mukogosi,Mayor's Office,M-Office of Mayor,Unpaid Intern Mayor,6/4/2018,6/4/2018,8/18/2018,0,F,Temporary,Black or African-American,$0.00,$0.00,$0.00,$0.00
4113,Daniel A Odu,Mayor's Office,M-Office of Mayor,Unpaid Intern Mayor,6/12/2018,6/12/2018,7/31/2018,0,M,Temporary,Black or African-American,$0.00,$0.00,$0.00,$0.00
4114,Omolade A Olubowale,Office Of Municipal Investigations,Office Of Municipal Investigations,Unpaid Intern OMI,6/11/2018,6/11/2018,NaN,0,F,Temporary,Black or African-American,$0.00,$0.00,$0.00,$0.00
4115,Benjamin S Perron,PS - Police Bureau,PS-Police Admin,Unpaid Intern Police,5/21/2018,5/21/2018,7/6/2018,0,M,Temporary,White,$0.00,$0.00,$0.00,$0.00
4116,Daniel A Pituch,Mobility & Infrastructure,Mobility & Infrastructure,Unpaid Intern DOMI,8/8/2018,8/8/2018,NaN,0,M,Temporary,White,$0.00,$0.00,$0.00,$0.00
4117,Eric J Shea,PW - Bureau Of Public Works Operations,PW-Properties,"Seasonal Laborer, AN",7/10/2017,7/10/2017,12/10/2017,0,M,Temporary,White,$0.00,$0.00,$0.00,$0.00
4118,Anna Rawls,City Planning,City Planning,Unpaid Intern City Planning,5/30/2018,5/30/2018,NaN,0,F,Temporary,White,$0.00,$0.00,$0.00,$0.00
4119,Keith J Robinson,PS - Administration and Support Service,PS-Public Safety/Admin,Unpaid Intern PS Admin 2,6/4/2018,6/4/2018,8/7/2018,0,M,Temporary,Black or African-American,$0.00,$0.00,$0.00,$0.00
4120,Oshea D Sulinski,ARAD - Public Works,PW-3rd Division,Rink Attendant-Temp PW,12/17/2018,12/17/2018,NaN,0,M,Temporary,White,$0.00,$0.00,$0.00,$0.00
4121,Christian J Sasala,City Council,Council Assistants,Unpaid Intern City Council,6/20/2018,6/20/2018,NaN,0,M,Temporary,White,$0.00,$0.00,$0.00,$0.00
4122,Gaetano S Scalise,PS - Administration and Support Service,PS-Public Safety/Admin,Unpaid Intern PS Admin 2,6/4/2018,6/4/2018,10/29/2018,0,M,Temporary,White,$0.00,$0.00,$0.00,$0.00
4123,Sarah M Scheid,Mayor's Office,M-Office of Mayor,Unpaid Intern Mayor,6/11/2018,6/11/2018,8/18/2018,0,F,Temporary,White,$0.00,$0.00,$0.00,$0.00
4124,Lydia Thompson,Parks And Recreation,PR-Swim Pool Maint,Pool Aide-Cashier,6/2/2018,6/2/2018,7/23/2018,0,F,Temporary,Black or African-American,$0.00,$0.00,$0.00,$0.00
4125,Kayla Sciulli,PS - Police Bureau,PS-Police Admin,Unpaid Intern Police,5/21/2018,5/21/2018,7/27/2018,0,F,Temporary,White,$0.00,$0.00,$0.00,$0.00
4126,Daniel J Tobin,Office Of Management And Budget,M-Office of Management & Budget,Sourcing Specialist,12/17/2018,12/17/2018,NaN,0,M,Full-time,White,$0.00,$0.00,$0.00,$0.00
4127,Claire M Sedlak,City Planning,City Planning,Unpaid Intern City Planning,5/15/2018,5/15/2018,NaN,0,F,Temporary,White,$0.00,$0.00,$0.00,$0.00
4128,Caroline E Seifert,City Planning,City Planning,Unpaid Intern City Planning,5/15/2018,5/15/2018,NaN,0,F,Temporary,White,$0.00,$0.00,$0.00,$0.00
4129,Min K Song,Mayor's Office,M-Office of Mayor,Unpaid Intern Mayor,5/14/2018,5/14/2018,8/18/2018,0,F,Temporary,Asian,$0.00,$0.00,$0.00,$0.00
4130,Macy Stalnaker,PS - Police Bureau,PS-Police Admin,Unpaid Intern Police,5/21/2018,5/21/2018,8/6/2018,0,F,Temporary,White,$0.00,$0.00,$0.00,$0.00
4131,Nthando Thandiwe,City Planning,City Planning,Unpaid Intern City Planning,9/27/2018,9/27/2018,NaN,0,M,Temporary,Black or African-American,$0.00,$0.00,$0.00,$0.00
4132,Eli C Tillman,Mayor's Office,M-Office of Mayor,Unpaid Intern Mayor,6/4/2018,6/4/2018,8/18/2018,0,M,Temporary,White,$0.00,$0.00,$0.00,$0.00
4133,Danielle T Vickers,City Planning,City Planning,Unpaid Intern City Planning,5/25/2018,5/25/2018,NaN,0,F,Temporary,Black or African-American,$0.00,$0.00,$0.00,$0.00
4134,Katrina T Vossler,City Council,Council Assistants,Unpaid Intern City Council,9/5/2018,9/5/2018,NaN,0,F,Temporary,White,$0.00,$0.00,$0.00,$0.00
4135,Maurice F White,PW - Bureau Of Public Works Operations,PW-Properties,Laborer-SH,12/17/2018,12/17/2018,NaN,0,M,Full-time,Hawaiian or Pacific Islander,$0.00,$0.00,$0.00,$0.00
4136,Samuel D White,Finance,FN-Finance/OBM,Unpaid Intern Finance,5/14/2018,5/14/2018,7/26/2018,0,M,Temporary,White,$0.00,$0.00,$0.00,$0.00
4137,Eric L Wright,PW - Bureau Of Public Works Operations,PW-2nd Division,Truck Driver Temporary,12/17/2018,12/17/2018,NaN,0,M,Temporary,Black or African-American,$0.00,$0.00,$0.00,$0.00
4138,Tyler P Wyckoff,PS - Administration and Support Service,PS-Public Safety/Admin,Unpaid Intern PS Admin 2,6/4/2018,6/4/2018,10/30/2018,0,M,Temporary,White,$0.00,$0.00,$0.00,$0.00
4139,Lindsay J Wynn,PS - Police Bureau,PS-Police Admin,Unpaid Intern Police,5/21/2018,5/21/2018,8/10/2018,0,F,Temporary,White,$0.00,$0.00,$0.00,$0.00
4140,Christina Yocca,PS - Police Bureau,PS-Police Admin,Unpaid Intern Police,5/21/2018,5/21/2018,6/29/2018,0,F,Temporary,White,$0.00,$0.00,$0.00,$0.00
4141,Lainey E Yockey,Innovation & Performance,M-City Information Systems,Unpaid Intern I&P 5,9/14/2017,9/14/2017,6/22/2018,0,X,Temporary,Unknown,$0.00,$0.00,$0.00,$0.00

↓ setting a variable for my DataFrame and taking a look to see what's inside

In [304]:
citysal = pd.read_csv("city_salaries_2018.csv")

In [305]:
citysal.head()

,Name,Department,Division (if applicable),Job Title,Date Started,Cur Pos Date,Date Term.,Years of Experience,Sex,Employment Status,Ethnic Code,Regular Pay,Premium Pay,Other Pay,Total Pay
0,Harry J Scherer,PS - Fire Bureau,PS-Fire-Gen Office,Deputy Chief,1/28/1980,5/17/2004,NaN,39,M,Full-time,White,"$120,645.87","$96,982.07",$0.00,"$217,627.94"
1,Jerome R Wasek,PS - Emergency Medical Services,PS-Emergency Medical Service,Crew Chief,10/31/1988,2/9/1997,NaN,30,M,Full-time,White,"$70,136.27","$145,649.73",$0.00,"$215,786.00"
2,Anthony N Desantis,PS - Emergency Medical Services,PS-Emergency Medical Service,Paramedic 5th Year,7/5/1994,1/1/2000,NaN,24,M,Full-time,White,"$64,842.21","$148,437.87",$0.00,"$213,280.08"
3,Francis M Rende,PS - Police Bureau,PS- Zone 2-Hill Dist,Master Police Officer,7/5/1993,4/29/2013,NaN,25,M,Full-time,White,"$81,883.15","$128,129.63",$0.00,"$210,012.78"
4,Robert J Cox,PS - Fire Bureau,PS-Fire-Gen Office,Deputy Chief,4/24/1995,1/21/2016,NaN,23,M,Full-time,White,"$112,194.61","$92,989.35",$0.00,"$205,183.96"

↓ doing an experiment to figure out if i can change the column names

In [306]:
citysal.rename(columns={'Name':'name'}, inplace=True)

In [307]:
citysal.head()

,name,Department,Division (if applicable),Job Title,Date Started,Cur Pos Date,Date Term.,Years of Experience,Sex,Employment Status,Ethnic Code,Regular Pay,Premium Pay,Other Pay,Total Pay
0,Harry J Scherer,PS - Fire Bureau,PS-Fire-Gen Office,Deputy Chief,1/28/1980,5/17/2004,NaN,39,M,Full-time,White,"$120,645.87","$96,982.07",$0.00,"$217,627.94"
1,Jerome R Wasek,PS - Emergency Medical Services,PS-Emergency Medical Service,Crew Chief,10/31/1988,2/9/1997,NaN,30,M,Full-time,White,"$70,136.27","$145,649.73",$0.00,"$215,786.00"
2,Anthony N Desantis,PS - Emergency Medical Services,PS-Emergency Medical Service,Paramedic 5th Year,7/5/1994,1/1/2000,NaN,24,M,Full-time,White,"$64,842.21","$148,437.87",$0.00,"$213,280.08"
3,Francis M Rende,PS - Police Bureau,PS- Zone 2-Hill Dist,Master Police Officer,7/5/1993,4/29/2013,NaN,25,M,Full-time,White,"$81,883.15","$128,129.63",$0.00,"$210,012.78"
4,Robert J Cox,PS - Fire Bureau,PS-Fire-Gen Office,Deputy Chief,4/24/1995,1/21/2016,NaN,23,M,Full-time,White,"$112,194.61","$92,989.35",$0.00,"$205,183.96"

↑ It worked! ↓ Changing the rest of the column names so they're a little easier to work with:

In [308]:
citysal.rename(columns={'Department':'dept'}, inplace=True)

In [309]:
citysal.rename(columns={'Division (if applicable)':'division'}, inplace=True)

In [310]:
citysal.rename(columns={'Job Title':'job_title'}, inplace=True)

In [311]:
citysal.rename(columns={'Date Started':'date_started'}, inplace=True)

In [312]:
citysal.rename(columns={'Cur Pos Date':'current_position_date'}, inplace=True)

In [313]:
citysal.rename(columns={'Date Term.':'date_term'}, inplace=True)

In [314]:
citysal.rename(columns={'Years of Experience':'yrs_experience'}, inplace=True)

In [315]:
citysal.rename(columns={'Sex ':'sex'}, inplace=True)

In [316]:
citysal.rename(columns={'Employment Status':'status'}, inplace=True)

In [317]:
citysal.rename(columns={'Ethnic Code':'race'}, inplace=True)

In [318]:
citysal.rename(columns={'Regular Pay':'regular_pay'}, inplace=True)

In [319]:
citysal.rename(columns={'Premium Pay':'premium_pay'}, inplace=True)

In [320]:
citysal.rename(columns={'Other Pay':'other_pay'}, inplace=True)

In [321]:
citysal.rename(columns={'Total Pay':'total_pay'}, inplace=True)

↓ Let's see if all of the changes worked

In [322]:
citysal.head()

,name,dept,division,job_title,date_started,current_position_date,date_term,yrs_experience,sex,status,race,regular_pay,premium_pay,other_pay,total_pay
0,Harry J Scherer,PS - Fire Bureau,PS-Fire-Gen Office,Deputy Chief,1/28/1980,5/17/2004,NaN,39,M,Full-time,White,"$120,645.87","$96,982.07",$0.00,"$217,627.94"
1,Jerome R Wasek,PS - Emergency Medical Services,PS-Emergency Medical Service,Crew Chief,10/31/1988,2/9/1997,NaN,30,M,Full-time,White,"$70,136.27","$145,649.73",$0.00,"$215,786.00"
2,Anthony N Desantis,PS - Emergency Medical Services,PS-Emergency Medical Service,Paramedic 5th Year,7/5/1994,1/1/2000,NaN,24,M,Full-time,White,"$64,842.21","$148,437.87",$0.00,"$213,280.08"
3,Francis M Rende,PS - Police Bureau,PS- Zone 2-Hill Dist,Master Police Officer,7/5/1993,4/29/2013,NaN,25,M,Full-time,White,"$81,883.15","$128,129.63",$0.00,"$210,012.78"
4,Robert J Cox,PS - Fire Bureau,PS-Fire-Gen Office,Deputy Chief,4/24/1995,1/21/2016,NaN,23,M,Full-time,White,"$112,194.61","$92,989.35",$0.00,"$205,183.96"

↓ Okay, now that the column names are changed, let's see what we've got:

In [323]:
citysal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4142 entries, 0 to 4141
Data columns (total 15 columns):
name                     4142 non-null object
dept                     4142 non-null object
division                 4142 non-null object
job_title                4142 non-null object
date_started             4142 non-null object
current_position_date    4142 non-null object
date_term                670 non-null object
yrs_experience           4142 non-null int64
sex                      4142 non-null object
status                   4142 non-null object
race                     4142 non-null object
regular_pay              4142 non-null object
premium_pay              4142 non-null object
other_pay                4142 non-null object
total_pay                4142 non-null object
dtypes: int64(1), object(14)
memory usage: 485.5+ KB

In [324]:
citysal.dtypes

name                     object
dept                     object
division                 object
job_title                object
date_started             object
current_position_date    object
date_term                object
yrs_experience            int64
sex                      object
status                   object
race                     object
regular_pay              object
premium_pay              object
other_pay                object
total_pay                object
dtype: object

↓ Figuring out that we have to get rid of the '$' figure and commas so we can do math on the numeric columns:

In [325]:
citysal['regular_pay'] = citysal['regular_pay'].str.replace('\$', '')

In [326]:
citysal['regular_pay'] = citysal['regular_pay'].str.replace('\,', '').astype(float)

In [327]:
citysal.head()

,name,dept,division,job_title,date_started,current_position_date,date_term,yrs_experience,sex,status,race,regular_pay,premium_pay,other_pay,total_pay
0,Harry J Scherer,PS - Fire Bureau,PS-Fire-Gen Office,Deputy Chief,1/28/1980,5/17/2004,NaN,39,M,Full-time,White,120645.87,"$96,982.07",$0.00,"$217,627.94"
1,Jerome R Wasek,PS - Emergency Medical Services,PS-Emergency Medical Service,Crew Chief,10/31/1988,2/9/1997,NaN,30,M,Full-time,White,70136.27,"$145,649.73",$0.00,"$215,786.00"
2,Anthony N Desantis,PS - Emergency Medical Services,PS-Emergency Medical Service,Paramedic 5th Year,7/5/1994,1/1/2000,NaN,24,M,Full-time,White,64842.21,"$148,437.87",$0.00,"$213,280.08"
3,Francis M Rende,PS - Police Bureau,PS- Zone 2-Hill Dist,Master Police Officer,7/5/1993,4/29/2013,NaN,25,M,Full-time,White,81883.15,"$128,129.63",$0.00,"$210,012.78"
4,Robert J Cox,PS - Fire Bureau,PS-Fire-Gen Office,Deputy Chief,4/24/1995,1/21/2016,NaN,23,M,Full-time,White,112194.61,"$92,989.35",$0.00,"$205,183.96"

In [328]:
citysal.dtypes

name                      object
dept                      object
division                  object
job_title                 object
date_started              object
current_position_date     object
date_term                 object
yrs_experience             int64
sex                       object
status                    object
race                      object
regular_pay              float64
premium_pay               object
other_pay                 object
total_pay                 object
dtype: object

Doing the rest:

In [329]:
citysal['premium_pay'] = citysal['premium_pay'].str.replace('\$', '')
citysal['other_pay'] = citysal['other_pay'].str.replace('\$', '')
citysal['total_pay'] = citysal['total_pay'].str.replace('\$', '')

In [330]:
citysal['premium_pay'] = citysal['premium_pay'].str.replace('\,', '').astype(float)
citysal['other_pay'] = citysal['other_pay'].str.replace('\,', '').astype(float)
citysal['total_pay'] = citysal['total_pay'].str.replace('\,', '').astype(float)

In [331]:
citysal.dtypes

name                      object
dept                      object
division                  object
job_title                 object
date_started              object
current_position_date     object
date_term                 object
yrs_experience             int64
sex                       object
status                    object
race                      object
regular_pay              float64
premium_pay              float64
other_pay                float64
total_pay                float64
dtype: object

↓ Looks like we're all set to procede

In [332]:
citysal.head()

,name,dept,division,job_title,date_started,current_position_date,date_term,yrs_experience,sex,status,race,regular_pay,premium_pay,other_pay,total_pay
0,Harry J Scherer,PS - Fire Bureau,PS-Fire-Gen Office,Deputy Chief,1/28/1980,5/17/2004,NaN,39,M,Full-time,White,120645.87,96982.07,0.0,217627.94
1,Jerome R Wasek,PS - Emergency Medical Services,PS-Emergency Medical Service,Crew Chief,10/31/1988,2/9/1997,NaN,30,M,Full-time,White,70136.27,145649.73,0.0,215786.00
2,Anthony N Desantis,PS - Emergency Medical Services,PS-Emergency Medical Service,Paramedic 5th Year,7/5/1994,1/1/2000,NaN,24,M,Full-time,White,64842.21,148437.87,0.0,213280.08
3,Francis M Rende,PS - Police Bureau,PS- Zone 2-Hill Dist,Master Police Officer,7/5/1993,4/29/2013,NaN,25,M,Full-time,White,81883.15,128129.63,0.0,210012.78
4,Robert J Cox,PS - Fire Bureau,PS-Fire-Gen Office,Deputy Chief,4/24/1995,1/21/2016,NaN,23,M,Full-time,White,112194.61,92989.35,0.0,205183.96

How many people did the City of Pittsburgh employ in 2018?

In [333]:
citysal.name.count()

4142

How many of the city's employees were full-time in 2018?

In [334]:
citysal.status[citysal.status == "Full-time"].count()

3527

↓ setting variables to do calculations on the "regular_pay," "premium_pay," "other_pay," and "total_pay" columns

In [335]:
regular_pay = citysal.regular_pay

In [336]:
premium_pay = citysal.premium_pay

In [337]:
other_pay = citysal.other_pay

In [338]:
total_pay = citysal.total_pay

How much did the city pay its workers in regular salaries and wages? And what was the median salary, based on regular earnings?

In [339]:
regular_pay.sum()

187151487.86

In [340]:
regular_pay.median()

47163.2

How much did city workers take home in total? And of that amount, what was the median earning?

In [341]:
total_pay.sum()

235676491.75

In [342]:
total_pay.median()

53163.14

How much overtime pay did city workers earn last year?

In [343]:
premium_pay.sum().round(2)

47887621.47

How much did city workers earn in bonuses and other pay last year?

In [344]:
other_pay.sum()

637382.42

Looking at the city's 2018 budget, we know it had budgeted $219,480,596 for employee salaries and wages (not including benefits like healthcare).

In [345]:
city_salary_budget = 219480596

So, was the city over or under budget in terms of employee pay?

In [346]:
(city_salary_budget - (citysal.total_pay.sum())).round(2)

-16195895.75

It looks like the city was over budget by about $16.2 million in terms of employee pay.

We know from years past that employees of the city's Public Safety department, made up of the bureaus of police, fire, emergency medical services and animal care and control, earn a lot of overtime. Let's take a look at how much overtime those employees earned in 2018.

In [347]:
police = citysal[citysal.dept == 'PS - Police Bureau']

In [348]:
fire_dept = citysal[citysal.dept == 'PS - Fire Bureau']
EMS = citysal[citysal.dept == 'PS - Emergency Medical Services']

In [349]:
police.premium_pay.sum()

24971855.48

In [350]:
fire_dept.premium_pay.sum()

13838677.89

In [351]:
EMS.premium_pay.sum().round(2)

5529869.52

Now let's look at the rest of the city departments. We can see in the table that the police, fire and EMS bureaus earned the most overtime pay. The calculations that follow look at each city department in terms of total regular_pay, other_pay and total_pay.

In [397]:
citysal.groupby("dept").premium_pay.sum().round().reset_index().sort_values("premium_pay", ascending=False).astype(str)

                                                 dept premium_pay
29                                 PS - Police Bureau  24971855.0
28                                   PS - Fire Bureau  13838678.0
27                    PS - Emergency Medical Services   5529870.0
31             PW - Bureau Of Public Works Operations   1677184.0
32                        PW - Environmental Services    875692.0
30                          PW - Bureau Of Facilities    246783.0
1                                 ARAD - Public Works    241104.0
22                          Mobility & Infrastructure    148216.0
26               PS - Bureau of Animal Care & Control    110376.0
34                               Parks And Recreation     63181.0
25            PS - Administration and Support Service     58011.0
16                           Innovation & Performance     35036.0
38                 Senior Citizens Program Trust Fund     24259.0
35                   Permits Licenses and Inspections     21399.0
0                                        ARAD - Parks     11772.0
6                                     City Controller      8847.0
11                                            Finance      5598.0
23                    Office Of Management And Budget      4636.0
17                Job Training Partnership Act (JTPA)      3459.0
9                       Commission on Human Relations      3345.0
33                       PW- Bureau Of Administration      3190.0
21                      Mellon Park Tennis Trust Fund      1890.0
8                                       City Planning      1258.0
15                      Human Resources/Civil Service       713.0
10                                       Ethics Board       398.0
4                         Citizen Police Review Board       342.0
14                      Hillman Transportation Fellow       151.0
12                        Green Initiative Trust Fund       124.0
41                           Three Taxing Bodies Fund       116.0
40             Special Summer Food Service Trust Fund        53.0
18                                                Law        45.0
39                          Special Events Trust Fund        42.0
20                          Mellon Innovation Roadmap         0.0
36                           Personnel- City Planning         0.0
2                  Bureau Of Neighborhood Empowerment         0.0
37                   Police Secondary Employment T.F.         0.0
7                                        City Council         0.0
3                                      CDBG Personnel         0.0
5                                          City Clerk         0.0
19                                     Mayor's Office         0.0
13                         Hillman Innovation Roadmap         0.0
24                 Office Of Municipal Investigations         0.0
42  Western PA Regional Data Center (paid for by H...         0.0

In [396]:
citysal.groupby("dept").regular_pay.sum().round().reset_index().sort_values("regular_pay", ascending=False).astype(str)

                                                 dept regular_pay
29                                 PS - Police Bureau  66371235.0
28                                   PS - Fire Bureau  44864258.0
31             PW - Bureau Of Public Works Operations  11269349.0
27                    PS - Emergency Medical Services  10751259.0
32                        PW - Environmental Services   7128537.0
22                          Mobility & Infrastructure   4060028.0
35                   Permits Licenses and Inspections   3945777.0
30                          PW - Bureau Of Facilities   3711375.0
16                           Innovation & Performance   3547290.0
6                                     City Controller   2829208.0
25            PS - Administration and Support Service   2773737.0
34                               Parks And Recreation   2545794.0
1                                 ARAD - Public Works   2540366.0
8                                       City Planning   2425568.0
11                                            Finance   2084747.0
15                      Human Resources/Civil Service   2015992.0
18                                                Law   1923557.0
7                                        City Council   1683135.0
23                    Office Of Management And Budget   1533702.0
38                 Senior Citizens Program Trust Fund   1145436.0
19                                     Mayor's Office   1021883.0
17                Job Training Partnership Act (JTPA)    882001.0
33                       PW- Bureau Of Administration    785532.0
2                  Bureau Of Neighborhood Empowerment    747652.0
5                                          City Clerk    656858.0
26               PS - Bureau of Animal Care & Control    627368.0
3                                      CDBG Personnel    555117.0
24                 Office Of Municipal Investigations    437019.0
41                           Three Taxing Bodies Fund    415035.0
9                       Commission on Human Relations    370393.0
4                         Citizen Police Review Board    355145.0
0                                        ARAD - Parks    327677.0
42  Western PA Regional Data Center (paid for by H...    199155.0
21                      Mellon Park Tennis Trust Fund    144495.0
40             Special Summer Food Service Trust Fund    120863.0
20                          Mellon Innovation Roadmap    103227.0
10                                       Ethics Board     88731.0
14                      Hillman Transportation Fellow     71401.0
36                           Personnel- City Planning     39968.0
37                   Police Secondary Employment T.F.     31295.0
39                          Special Events Trust Fund     15529.0
12                        Green Initiative Trust Fund      4678.0
13                         Hillman Innovation Roadmap       117.0

In [395]:
citysal.groupby("dept").other_pay.sum().round().reset_index().sort_values("other_pay", ascending=False).astype(str)

                                                 dept other_pay
32                        PW - Environmental Services  161387.0
29                                 PS - Police Bureau   90147.0
8                                       City Planning   45918.0
28                                   PS - Fire Bureau   42440.0
27                    PS - Emergency Medical Services   39746.0
31             PW - Bureau Of Public Works Operations   31077.0
7                                        City Council   30383.0
16                           Innovation & Performance   19446.0
35                   Permits Licenses and Inspections   18991.0
22                          Mobility & Infrastructure   18429.0
1                                 ARAD - Public Works   16280.0
11                                            Finance   14940.0
25            PS - Administration and Support Service   12492.0
17                Job Training Partnership Act (JTPA)   12295.0
6                                     City Controller    9650.0
15                      Human Resources/Civil Service    9650.0
30                          PW - Bureau Of Facilities    9479.0
38                 Senior Citizens Program Trust Fund    9435.0
5                                          City Clerk    9346.0
18                                                Law    6640.0
34                               Parks And Recreation    6500.0
23                    Office Of Management And Budget    6100.0
33                       PW- Bureau Of Administration    3100.0
2                  Bureau Of Neighborhood Empowerment    2630.0
3                                      CDBG Personnel    2340.0
19                                     Mayor's Office    1520.0
24                 Office Of Municipal Investigations    1440.0
9                       Commission on Human Relations    1380.0
4                         Citizen Police Review Board    1380.0
41                           Three Taxing Bodies Fund    1200.0
0                                        ARAD - Parks     720.0
40             Special Summer Food Service Trust Fund     480.0
42  Western PA Regional Data Center (paid for by H...     240.0
20                          Mellon Innovation Roadmap     180.0
26               PS - Bureau of Animal Care & Control       0.0
14                      Hillman Transportation Fellow       0.0
36                           Personnel- City Planning       0.0
37                   Police Secondary Employment T.F.       0.0
13                         Hillman Innovation Roadmap       0.0
39                          Special Events Trust Fund       0.0
12                        Green Initiative Trust Fund       0.0
10                                       Ethics Board       0.0
21                      Mellon Park Tennis Trust Fund       0.0

In [394]:
citysal.groupby("dept").total_pay.sum().round().reset_index().sort_values("total_pay", ascending=False).astype(str)

                                                 dept   total_pay
29                                 PS - Police Bureau  91433237.0
28                                   PS - Fire Bureau  58745376.0
27                    PS - Emergency Medical Services  16320875.0
31             PW - Bureau Of Public Works Operations  12977610.0
32                        PW - Environmental Services   8165615.0
22                          Mobility & Infrastructure   4226673.0
35                   Permits Licenses and Inspections   3986167.0
30                          PW - Bureau Of Facilities   3967637.0
16                           Innovation & Performance   3601772.0
6                                     City Controller   2847705.0
25            PS - Administration and Support Service   2844240.0
1                                 ARAD - Public Works   2797751.0
34                               Parks And Recreation   2615474.0
8                                       City Planning   2472743.0
11                                            Finance   2105286.0
15                      Human Resources/Civil Service   2026355.0
18                                                Law   1930242.0
7                                        City Council   1713518.0
23                    Office Of Management And Budget   1544437.0
38                 Senior Citizens Program Trust Fund   1179129.0
19                                     Mayor's Office   1023403.0
17                Job Training Partnership Act (JTPA)    897755.0
33                       PW- Bureau Of Administration    791822.0
2                  Bureau Of Neighborhood Empowerment    750282.0
26               PS - Bureau of Animal Care & Control    737743.0
5                                          City Clerk    666204.0
3                                      CDBG Personnel    557457.0
24                 Office Of Municipal Investigations    438459.0
41                           Three Taxing Bodies Fund    416351.0
9                       Commission on Human Relations    375118.0
4                         Citizen Police Review Board    356867.0
0                                        ARAD - Parks    340169.0
42  Western PA Regional Data Center (paid for by H...    199395.0
21                      Mellon Park Tennis Trust Fund    146385.0
40             Special Summer Food Service Trust Fund    121396.0
20                          Mellon Innovation Roadmap    103407.0
10                                       Ethics Board     89129.0
14                      Hillman Transportation Fellow     71553.0
36                           Personnel- City Planning     39968.0
37                   Police Secondary Employment T.F.     31295.0
39                          Special Events Trust Fund     15571.0
12                        Green Initiative Trust Fund      4802.0
13                         Hillman Innovation Roadmap       117.0

In [356]:
citysal.head()

,name,dept,division,job_title,date_started,current_position_date,date_term,yrs_experience,sex,status,race,regular_pay,premium_pay,other_pay,total_pay
0,Harry J Scherer,PS - Fire Bureau,PS-Fire-Gen Office,Deputy Chief,1/28/1980,5/17/2004,NaN,39,M,Full-time,White,120645.87,96982.07,0.0,217627.94
1,Jerome R Wasek,PS - Emergency Medical Services,PS-Emergency Medical Service,Crew Chief,10/31/1988,2/9/1997,NaN,30,M,Full-time,White,70136.27,145649.73,0.0,215786.00
2,Anthony N Desantis,PS - Emergency Medical Services,PS-Emergency Medical Service,Paramedic 5th Year,7/5/1994,1/1/2000,NaN,24,M,Full-time,White,64842.21,148437.87,0.0,213280.08
3,Francis M Rende,PS - Police Bureau,PS- Zone 2-Hill Dist,Master Police Officer,7/5/1993,4/29/2013,NaN,25,M,Full-time,White,81883.15,128129.63,0.0,210012.78
4,Robert J Cox,PS - Fire Bureau,PS-Fire-Gen Office,Deputy Chief,4/24/1995,1/21/2016,NaN,23,M,Full-time,White,112194.61,92989.35,0.0,205183.96

What do the city's demographics look like?

In [357]:
citysal.groupby("race").name.count().reset_index().sort_values("name", ascending=False).astype(str)

                             race  name
8                           White  3143
2       Black or African-American   806
4              Hispanic or Latino    51
1                           Asian    50
7                         Unknown    48
6               Two or More Races    34
0  American Indian/Alaskan Native     8
3    Hawaiian or Pacific Islander     1
5         Other Pacific Islanders     1

Below are three tables showing all of the male, female and other employees who worked for the City of Pittsburgh, broken down by race:

In [358]:
citysal.groupby(citysal.race[citysal.sex == "M"]).sex.count().reset_index().sort_values("sex", ascending=False)

                             race   sex
7                           White  2376
2       Black or African-American   546
4              Hispanic or Latino    33
1                           Asian    26
6                         Unknown    21
5               Two or More Races    19
0  American Indian/Alaskan Native     4
3    Hawaiian or Pacific Islander     1

In [359]:
citysal.groupby(citysal.race[citysal.sex == "F"]).sex.count().reset_index().sort_values("sex", ascending=False)

                             race  sex
7                           White  763
2       Black or African-American  260
1                           Asian   24
3              Hispanic or Latino   18
5               Two or More Races   15
6                         Unknown   15
0  American Indian/Alaskan Native    4
4         Other Pacific Islanders    1

In [360]:
citysal.groupby(citysal.race[citysal.sex == "X"]).sex.count().reset_index().sort_values("sex", ascending=False)

      race  sex
0  Unknown   12
1    White    4

Now, let's compare demographics to regular_pay, premium_pay, other_pay and total_pay. All salary calculations are listed as medians, as those figures show us what an average employee in these subgroups earned.

In [382]:
citysal.groupby("race").regular_pay.median().round().reset_index().sort_values("regular_pay", ascending=False).astype(str)

                             race regular_pay
8                           White     51959.0
4              Hispanic or Latino     49069.0
2       Black or African-American     40502.0
0  American Indian/Alaskan Native     29251.0
1                           Asian     25331.0
7                         Unknown     16469.0
5         Other Pacific Islanders     13970.0
6               Two or More Races      3631.0
3    Hawaiian or Pacific Islander         0.0

In [381]:
citysal.groupby("race").premium_pay.median().round().reset_index().sort_values("premium_pay", ascending=False).astype(str)

                             race premium_pay
0  American Indian/Alaskan Native      4648.0
8                           White      4340.0
2       Black or African-American      1987.0
4              Hispanic or Latino      1866.0
1                           Asian         0.0
3    Hawaiian or Pacific Islander         0.0
5         Other Pacific Islanders         0.0
6               Two or More Races         0.0
7                         Unknown         0.0

In [384]:
citysal.groupby("race").total_pay.median().round().reset_index().sort_values("total_pay", ascending=False).astype(str)

                             race total_pay
8                           White   60068.0
4              Hispanic or Latino   49464.0
2       Black or African-American   45032.0
0  American Indian/Alaskan Native   33395.0
1                           Asian   26876.0
7                         Unknown   16770.0
5         Other Pacific Islanders   13970.0
6               Two or More Races    3631.0
3    Hawaiian or Pacific Islander       0.0

Now let's see how the city workforce breaksdown in terms of sex - and the salaries that men, women and others earn.

In [365]:
citysal.groupby("sex").name.count().reset_index().sort_values("name", ascending=False).astype(str)

  sex  name
1   M  3026
0   F  1100
2   X    16

In [390]:
citysal.groupby("sex").regular_pay.median().round().reset_index().sort_values("regular_pay", ascending=False).astype(str)

  sex regular_pay
1   M     52729.0
0   F     31983.0
2   X     24620.0

In [391]:
citysal.groupby("sex").premium_pay.median().round().reset_index().sort_values("premium_pay", ascending=False).astype(str)

  sex premium_pay
1   M      6533.0
2   X        15.0
0   F         0.0

In [393]:
citysal.groupby("sex").total_pay.median().round().reset_index().sort_values("total_pay", ascending=False).astype(str)

  sex total_pay
1   M   62298.0
0   F   32924.0
2   X   26237.0

Grouping city employees into salary brackets can give a sense of how pay is distributed among the entire city workforce. For example, the salary brackets below show that 1,204 city employees earn between $60,000 and $80,000 per year but that the majority of the city’s workforce — 64 percent — earn less than $60,000 per year.

In [371]:
regular_pay = citysal.regular_pay

In [372]:
regular_pay[regular_pay > 200000].count()

0

In [373]:
regular_pay[regular_pay > 100000][regular_pay < 200000].count()

44

In [374]:
regular_pay[regular_pay > 80000][regular_pay < 100000].count()

244

In [375]:
regular_pay[regular_pay > 60000][regular_pay < 80000].count()

1204

In [376]:
regular_pay[regular_pay > 40000][regular_pay < 60000].count()

1106

In [377]:
regular_pay[regular_pay > 20000][regular_pay < 40000].count()

556

In [378]:
regular_pay[regular_pay < 20000].count()

988

Now let's look at the top 25 earners in the city workforce, based on gross pay.

In [387]:
citysal.sort_values("total_pay", ascending=False)[:25]

,name,dept,division,job_title,date_started,current_position_date,date_term,yrs_experience,sex,status,race,regular_pay,premium_pay,other_pay,total_pay
0,Harry J Scherer,PS - Fire Bureau,PS-Fire-Gen Office,Deputy Chief,1/28/1980,5/17/2004,NaN,39,M,Full-time,White,120645.87,96982.07,0.0,217627.94
1,Jerome R Wasek,PS - Emergency Medical Services,PS-Emergency Medical Service,Crew Chief,10/31/1988,2/9/1997,NaN,30,M,Full-time,White,70136.27,145649.73,0.0,215786.00
2,Anthony N Desantis,PS - Emergency Medical Services,PS-Emergency Medical Service,Paramedic 5th Year,7/5/1994,1/1/2000,NaN,24,M,Full-time,White,64842.21,148437.87,0.0,213280.08
3,Francis M Rende,PS - Police Bureau,PS- Zone 2-Hill Dist,Master Police Officer,7/5/1993,4/29/2013,NaN,25,M,Full-time,White,81883.15,128129.63,0.0,210012.78
4,Robert J Cox,PS - Fire Bureau,PS-Fire-Gen Office,Deputy Chief,4/24/1995,1/21/2016,NaN,23,M,Full-time,White,112194.61,92989.35,0.0,205183.96
5,May G Fong,PS - Police Bureau,PS- Zone 3-Southside,Police Sergeant,9/6/1983,7/7/1995,NaN,35,F,Full-time,Asian,85921.60,113059.78,0.0,198981.38
6,Terry A Pryor,PS - Police Bureau,PS- Zone 2-Hill Dist,Police Officer 4th Year,2/5/2007,2/5/2010,NaN,12,M,Full-time,Black or African-American,70211.96,127485.59,0.0,197697.55
7,Police Officer Detective,PS - Police Bureau,PS-Police-Major Crimes,Police Officer/Detective,7/5/1993,4/6/1998,NaN,25,M,Full-time,White,76043.33,120759.19,480.0,197282.52
8,Igor S Boyko,PS - Police Bureau,PS- Zone 2-Hill Dist,Police Officer 4th Year,2/5/2007,2/5/2010,NaN,12,M,Full-time,White,69169.19,124404.33,480.0,194053.52
9,Mark B Gasiorowski,PS - Fire Bureau,PS-Fire-Gen Office,Deputy Chief-2010,8/9/1999,8/20/2018,NaN,19,M,Full-time,White,94742.92,98779.85,240.0,193762.77
10,Michael J Mullen,PS - Fire Bureau,PS-Fire-Gen Office,Deputy Chief,12/18/1974,5/12/2008,NaN,44,M,Full-time,White,120126.39,73550.72,0.0,193677.11
11,Sean E Duffy,PS - Police Bureau,PS-Special Deployment Div,Police Sergeant,4/9/1990,9/25/1998,NaN,28,M,Full-time,White,87119.83,104837.48,0.0,191957.31
12,Dominick C Sciulli,PS - Police Bureau,PS-Warrant Office,Police Lieutenant,1/14/2004,7/27/2015,NaN,15,M,Full-time,White,91617.23,96509.35,0.0,188126.58
13,Police Officer Detective,PS - Police Bureau,PS-Police-Narcotics/Vice,Police Officer/Detective,2/20/1995,4/13/2004,NaN,24,M,Full-time,White,74511.38,107063.52,0.0,181574.90
14,Glenn E Aldridge,PS - Police Bureau,PS-Special Deployment Div,Master Police Officer,4/17/1989,4/17/2004,NaN,29,M,Full-time,Black or African-American,76511.00,103380.71,0.0,179891.71
15,Gregory S Tersine,PS - Emergency Medical Services,PS-Emergency Medical Service,Crew Chief,10/17/2005,9/11/2011,NaN,13,M,Full-time,White,63885.87,115050.66,0.0,178936.53
16,Roy C Mcdonald,PS - Fire Bureau,PS-Fire-Gen Office,Battalion Chief,3/23/1987,1/9/2006,NaN,31,M,Full-time,White,111281.70,66665.78,240.0,178187.48
17,Phillip A Carey,PS - Police Bureau,PS-Chief Of Police,Police Sergeant,1/16/1995,2/22/2018,NaN,24,M,Full-time,Black or African-American,84180.05,90894.68,0.0,175074.73
18,Chad M O'Brien,PS - Police Bureau,PS- Zone 2-Hill Dist,Police Lieutenant,1/24/2005,8/16/2017,NaN,14,M,Full-time,White,92761.81,80335.92,0.0,173097.73
19,Daniel A Berg,PS - Emergency Medical Services,PS-Emergency Medical Service,Paramedic 5th Year,10/17/2005,10/17/2009,NaN,13,M,Full-time,White,66616.97,105444.36,0.0,172061.33
20,Antwain R Carter,PS - Emergency Medical Services,PS-EMS Admin,District Chief,1/3/1995,9/10/2018,NaN,24,M,Full-time,Black or African-American,74101.11,94901.92,0.0,169003.03
21,William S Hohos,PS - Police Bureau,PS- Zone 2-Hill Dist,Police Sergeant,7/5/1993,1/14/2005,NaN,25,M,Full-time,White,83651.43,85030.95,240.0,168922.38
22,Jeffrey C Vesci,PS - Emergency Medical Services,PS-Emergency Medical Service,Paramedic 5th Year,6/19/1989,1/1/2000,NaN,29,M,Full-time,White,61941.06,106674.05,0.0,168615.11
23,Joseph F Tersak,PS - Police Bureau,PS-Special Deployment Div,Police Lieutenant,4/4/1988,12/15/2003,NaN,30,M,Full-time,White,94863.81,71259.87,0.0,166123.68
24,James A Yauch,PS - Police Bureau,PS- Zone 6-West End,Police Sergeant,10/29/2007,11/9/2015,NaN,11,M,Full-time,White,80444.96,83980.13,0.0,164425.09